### ISSUE TITLE
OS X recipe failing on `make check` step of build.

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/glpk-feedstock#3] opened 2016-03-28 15:46 UTC
The OS X CI build is [failing in the `make check` step](https://travis-ci.org/conda-forge/glpk-feedstock/builds/118982300) due to the incorrect libgmp being loaded.  The error is:

```
+ make check
Making check in src
make[1]: Nothing to be done for `check'.
Making check in examples
./glpsol --version
dyld: Library not loaded: @rpath/libgmp.10.dylib
  Referenced from: /Users/travis/miniconda3/conda-bld/work/glpk-4.59/examples/.libs/glpsol
  Reason: Incompatible library version: glpsol requires version 14.0.0 or later, but libgmp.10.dylib provides version 13.0.0
make[1]: *** [check] Trace/BPT trap: 5
make: *** [check-recursive] Error 1
Command failed: /bin/bash -x -e /Users/travis/build/conda-forge/glpk-feedstock/recipe/build.sh
```

I think the brew libgmp may be picked up by the loader which is causing this issue.  I'm do not know why an earlier run of this build in PR #2 [was successful](https://travis-ci.org/conda-forge/glpk-feedstock/builds/118457891).

**Comment by jakirkham** [comment] 2016-03-28 15:47
Yes, the problem is it is using GMP from brew. Try using [this]( https://github.com/conda-forge/mpfr-feedstock/blob/master/recipe/build.sh#L15 ).

**Comment by jakirkham** [comment] 2016-03-28 15:48
Probably we should eliminate everything from brew as it is becoming a nuisance.

**Comment by jakirkham** [comment] 2016-03-28 15:56
Added this issue ( https://github.com/conda-forge/conda-smithy/issues/103 ) so that we can take a look at just purging brew in all cases. We don't want to accidentally become somewhat dependent on brew IMHO. So, we should just start purging it completely and see what we may still need as dependencies in our packaging ecosystem. Perhaps some select things will be installed afterwards.

**Comment by jjhelmus** [comment] 2016-03-28 15:57
I don't think the LD_LIBRARY_PATH trick will work because the variables is not exported in the makefile.  I'll submit a PR to check but at least on my Mac (with no system libgmp) I still get an image missing error.

**Comment by jakirkham** [comment] 2016-03-28 16:00
So, maybe something is broken with our `gmp`.

**Comment by jakirkham** [comment] 2016-03-28 16:20
Looks like it does work, but we should definitely move away from having to do this. The greatest benefit of CI is we can use a minimal image to build and test what we need. At present, it doesn't feel minimal enough.

**Closed** 2016-03-28 17:33 UTC
